spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth_example?createDatabaseIfNotExist=true
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql
    username: root
    password: password
  jpa:
    database: MySQL
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8093
logging:
  level:
    org.springframework.security: TRACE
    com.oauth2.example: DEBUG


